package net.xicp.jeason.Engine.utils;

import javax.swing.ImageIcon;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : @EasyEngine
//  @ File Name : Resource.java
//  @ Date : 2015/6/3
//  @ Author : @Jeason1997
//
//

public class Resource{
	
	public ImageIcon logo;
	public ImageIcon helloWorld;
	
	public Resource() {
		logo = new ImageIcon(getClass().getResource("/LOGO.png"));
		helloWorld = new ImageIcon(getClass().getResource("/helloworld.png"));
	}
}


